#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - postgresql-client
  - build-essential
  - pkg-config
  - libssl-dev
runcmd:
  # Install Rust (in case user wants to compile directly on the VM)
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  # Setup application and log directories
  - mkdir -p /var/www/sleekly-backend/uploads
  - mkdir -p /var/log/sleekly-backend
  - chown -R azureuser:azureuser /var/www/sleekly-backend
  - chown -R azureuser:azureuser /var/log/sleekly-backend
