#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - nginx
runcmd:
  # Install Node.js 20.x
  - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  - apt-get install -y nodejs
  # Install PM2 globally
  - npm install -g pm2
  # Start Nginx
  - systemctl enable nginx
  - systemctl start nginx
